### ISSUE TITLE
All-compressed instructions parsing of 00/11 to 1/0

### ISSUE THREAD

**Issue by gdelazzari** [cnlohr/rv003usb#2]
While watching the recording of the live stream, I thought about this solution when, around 1:16:00 of part 2.5, you were looking for a set of two compressed instructions for parsing `00` into `1` and `11` into `0` in the `a0` register here:

https://github.com/cnlohr/rv003usb/blob/200e619cb46523901ffe8572bc0a9394383bc049/firmware/rv003usb.S#L116-L117

What about
```gas
c.addi a0, 1 // 00 -> 1, 11 -> 100
c.andi a0, 1 // 1 -> 1, 100 -> 0
```
?

I can't test this, so I'm not submitting a PR.
Also, I reckon this doesn't make a big difference (2 bytes saved in FLASH?) but maybe it can add up to other small savings if, in the future, code size has to be minimized.

**Comment by cnlohr** [comment]
Woweee!!! That looks like it might be a winrar.  It is more and more important to use only compressed instructions on any core part of a loop.  Not just in saved flash, but also uncompressed instructions seem to sometimes take two cycles instead of one :(

Right now this is what I have:

```as
	lw a0, INDR_OFFSET(a5);
	c.andi a0, USB_DMASK;
	c.beqz a0, se0_complete
	c.xor a0, a1;
	c.xor a1, a0; // Recover a1, for next cycle.
	// a0 is either 00 for 1 or 11 for 0, anything else is error.
	c.mv a4, a0
	c.slli a4, 1  // a4 is 6 if it's a 0 bit.
	c.or a4, a0   // a4 is 7 if it's a 0 bit.
	c.or s0, a4   // s0 becomes 7 if it's a 0 bit.
	c.addi s0, -1 // Count # of runs of 1 (subtract 1)
	c.beqz s0, handle_bit_stuff
	xori a0, a0, 3 //00 for 0 or 11 for 1. // THIS TAKES 2 CYCLES
	c.andi a0, 1  //0 for 0 and 1 for 1.
```

Your change absolutely is a big help at the end.  I might be able to do things out-of-order

```as
	c.addi a0, 1 // 00 -> 1, 11 -> 100
	c.andi a0, 1 // 1 -> 1, 100 -> 0
	c.or a2, a0
	// Then...
	c.addi a0, -1 // 0->0xffffffff 1->0
	c.ori s0, a0
	c.andi s0, 7
```

Boom! I'm not sure if this works, but if it does it would be neat.

**Comment by cnlohr** [comment]
This has all been implemented.  Thank you for the input.

**Comment by gdelazzari** [comment]
I only managed to sort-of catch up with the streams now. I'm glad to hear that a solution was found!
Keep up the good work :)
